# Base config

languageCode = "en-us"
baseURL = "http://paganini.net/"

author = "Marco Paganini"
title = "paganini.net"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
# googleAnalytics = "XYZ"
# enableRobotsTXT = true

## Site Settings
[params]
author = "Marco Paganini"
intro = "A website without much to say"
#description = "A brief view into my world."

authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Homepage for Marco Paganini <paganini@paganini.net>"
keywords = "google,deserts,mountain-biking,pictures,geek,resume"

## Social Accounts
[params.social]
github = "marcopaganini"
linkedin = "paganini"
twitter = "donpaganini"
google = "+MarcoPaganini"
email = "paganini@paganini.net"
#stackoverflow = "<username>"
#instagram = "<username>"
#facebook = "<username>"

## Extras
[params.extra]
copyright = "© by Marco Paganini" 
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "resume"
    weight = 100
    identifier = "resume"
    url = "/resume"
#[[menu.main]]
#    name = "about"
#    identifier = "about"
#    weight = 200
#    url = "/about/"
#[[menu.main]]
#    name = "coderag"
#    identifier = "coderag"
#    weight = 300
#    url = "/coderag/"
